# MODIFICAR FILAS / ACTUALIZAR DATOS #
# SE ACTULIZA TODA LA COLUMNA DE fecha A LA VEZ #
UPDATE usuarios SET fecha=CURDATE();
# SE ACTUALIZA SOLO EL id 4 #
UPDATE usuarios SET fecha='2019-07-09' WHERE id = 4;



